#!/bin/bash

echo "Hello $USER,"
echo "Welke Repo wil je gebruiken?"

echo "niet school ---- = 1"
echo "school---------- = 2"
echo "exit ----------- = 3"

read choice

option1=1
option2=2

#Niet school

if [ $choice == $option1 ]; then
    rm "/etc/apt/sources.list"
    echo "een repo-server wordt ingesteld: ftp.debian.org"
    cat "/etc/apt/sources.list" > "/etc/apt/sources.list"
    echo "deb http://ftp.nl.debian.org/debian stretch main" > "/etc/apt/sources.list"
    apt update
    echo "je kan weer software installeren!"
#School
elif [ $choice == $option2 ]; then
    rm "/etc/apt/sources.list"
    echo "repo-server van school wordt ingesteld: 10.203.216.40!"
    cat "/etc/apt/sources.list" > "/etc/apt/sources.list"
    echo "deb http://10.203.216.40/debian stretch main" > "/etc/apt/sources.list"
    apt update
    echo "je kan weer software installeren!"
fi




